# Dependabot configuration file
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm (frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    # Specify labels for npm pull requests
    labels:
      - "npm"
      - "dependencies"
    # Set a limit on the number of open pull requests for npm dependencies
    open-pull-requests-limit: 10
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Specify labels for GitHub Actions pull requests
    labels:
      - "github-actions"
      - "dependencies"
    # Set a limit on the number of open pull requests for GitHub Actions
    open-pull-requests-limit: 5